package postgis

const (
	FnGeomFromGeoJSON        = "ST_GeomFromGeoJSON"
	FnAsGeoJSON              = "ST_AsGeoJSON"
	FnDWithin                = "ST_DWithin"
	FnDistance               = "ST_Distance"
	FnIntersects             = "ST_Intersects"
	FnTransform              = "ST_Transform"
	FnMakeEnvelope           = "ST_MakeEnvelope"
	FnAsMVT                  = "ST_AsMVT"
	FnAsMVTGeom              = "ST_AsMVTGeom"
	FnSimplifyPreserveToplogy = "ST_SimplifyPreserveTopology"
	FnXMin                   = "ST_XMin"
	FnXMax                   = "ST_XMax"
	FnYMin                   = "ST_YMin"
	FnYMax                   = "ST_YMax"
	FnCentroid               = "ST_Centroid"
	FnAsRaster               = "ST_AsRaster"
	FnTile                   = "ST_Tile"
	FnUnion                  = "ST_Union"
	FnCollect                = "ST_Collect"
	FnEnvelope               = "ST_Envelope"
	FnSRID                   = "ST_SRID"
	FnSetSRID                = "ST_SetSRID"
)
